### ISSUE TITLE
Demonstrate setup-ocaml v2

### ISSUE THREAD

**Issue by leviroth** [avsm/hello-world-action-ocaml#3]
The action currently uses v1, and there's been at least one breaking change (`ocaml-version` => `ocaml-compiler`). It would be nice to see an updated version with setup-ocaml v2.

**Comment by smorimoto** [comment]
Indeed, I will work on it

**Comment by smorimoto** [comment]
Done in 7f687ecbeae1082e6ef059ab32e13510326112ed
